### ISSUE TITLE
Injecting into IRequestStartup

### ISSUE THREAD

**Issue by tpluscode** [lcssk8board/Nancy.Bootstrappers.DryIoc#2]
Hi. I'm experimenting with various bootstrappers, because I've found the hard way that they don't all act the same. DryIoc generally looks good so that's a :+1: 

However there is a problem where it's not possible to inject a pre-request dependency into implementations of `IRequestStartup`. The error is 

> DryIoc.ContainerExceptionUnable to resolve Nancy.Bootstrapper.TestSubjects.RequestStartupWithPerRequestInjection: Nancy.Bootstrapper.IRequestStartup {ServiceKey=DefaultKey.Of(0), ReturnDefault}
>   in wrapper IEnumerable<Nancy.Bootstrapper.IRequestStartup>
> Where CurrentScope: {Name=WebRequestScopeName}
>   and ResolutionScope: null
>   and Found registrations:
>   DefaultKey.Of(0),{ID=124, ImplType=Nancy.Bootstrapper.TestSubjects.RequestStartupWithPerRequestInjection, Reuse=SingletonReuse {Lifespan=1000}}}

For reference please see Test 6 in [my repository](https://github.com/tpluscode/Nancy.Boostrapper.Experiments/)

**Comment by lucascebertin** [comment]
Hello, thanks for opening the issue and for sharing the test repo.

I will look it and try to find a solution as soon as possible.

**Comment by dadhi** [comment]
In RegisterAndGetRequestStartupTasks replace with Reuse.InWebRequest, and check against the provided test 6. ?

**Comment by dadhi** [comment]
Another small improvement in RegisterAndGetRequestStartupTasks method might be passing IfAlreadyRegistered.Keep argument to RegisterMany. It will ensure register once semantic, and will guard from multiple calls to register startup tasks method.

**Comment by lucascebertin** [comment]
@dadhi, I've tried to change that like you recommend but inside the method, after the registration process (using any kind of Reuse type) the IStartupRequest still can't be resolved... I tried to change to InWebRequest and to IfAlreadyRegistered to Keep.

I still debugging it but if you see anything to point the direction, feel free to tell me.

Sorry the delay guys...

**Comment by dadhi** [comment]
@lcssk8board, I will look Tomorrow.

**Comment by dadhi** [comment]
Ok, that's quite interesting. The issue is that StartupTaskRegistrations happen twice, therefore DryIoc unable to select from multiple. I am guessing that PerRequest registrations into scoped container should be done as IfAlreadyRegistered.Keep. Haven't enough time to check. Will procceed Tomorrow.

**Comment by dadhi** [comment]
To provide a proper fix I need to fix https://bitbucket.org/dadhi/dryioc/issues/263
Hopefully Tomorrow.

**Comment by dadhi** [comment]
It will take longer, cause new fixes need to be integrated into v2.3.

**Comment by dadhi** [comment]
Sorry, I meant v2.4. Published Today. 

I submitted the PR that fixes the tests.

**Comment by lucascebertin** [comment]
Nice, already merged.
I'll try and @tpluscode can confirm the fix.

**Comment by lucascebertin** [comment]
All the unit tests are passing right now.

I've uploaded a new version to nuget, now the DryIoc.dll version is 2.4.0

Thanks @dadhi

**Comment by tpluscode** [comment]
Great work guys. Thanks!

**Comment by dadhi** [comment]
Great :)
